@startuml

participant "KeyC :HTMLElement" as KeyC
participant ":ZahlLöschen" as ZahlLöschen
participant ":CalculatorContext" as CalculatorContext
participant "Display :HTMLElement" as Display

KeyC -> ZahlLöschen: keyCPressed()
ZahlLöschen -> CalculatorContext: setDisplayValue()
CalculatorContext -> Display: set innerText()

@enduml